### ISSUE TITLE
Why swap control and caps?

### ISSUE THREAD

**Issue by zenshinji** [freetonik/castlemacs#11]
Is there something specific to this configuration where it is beneficial to swap control and caps?

Also, not all keyboards have caps and control in the same spots as the US QUERTY keyboard. On the Japanese Apple keyboard (JIS), control is left of A and caps is left of option, for example.

**Comment by freetonik** [comment]
>Is there something specific to this configuration where it is beneficial to swap control and caps?

There is nothing specific to this config. Actually, `Control` is supposedly _less_ used in Castlemacs, because many common functions are invoked via `Command`, so, this suggestion to map Caps Lock to Control is a tiny bit less relevant for Castlemacs than for Vanilla Emacs.

Control is one the most heavily used modifier keys in Emacs, and having a larger button closer to the home row for that is just better ergonomically (far from perfect, nevertheless). It requires less movement and a more comfortable angle for the left pinky. Google "why emacs caps lock" for a variety of motivations and explanations.

>Also, not all keyboards have caps and control in the same spots as the US QUERTY keyboard. On the Japanese Apple keyboard (JIS), control is left of A and caps is left of option, for example.

Woah, this is an interesting detail I haven't considered!

![mla22j](https://user-images.githubusercontent.com/2665931/46242973-59fdf280-c3d7-11e8-9b49-06032c600988.jpg)

I guess, for this type of layout you don't really need to change anything. I should add this to the documentation.
