### ISSUE TITLE
 Package ‘undo-tree-’ is unavailable

### ISSUE THREAD

**Issue by jonaprieto** [freetonik/castlemacs#21]
```
Error (use-package): Failed to install undo-tree: Package ‘undo-tree-’ is unavailable
Error (use-package): undo-tree/:init: Symbol’s function definition is void: global-undo-tree-mode
Error (use-package): Cannot load undo-tree
```

**Comment by mmrezaie** [comment]
I believe you this problem is becasue of a bug in emacs 26.2 (https://debbugs.gnu.org/34341) and you can add this line to start of your init.el and you can normaly install from elpa:
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")

You can read more about this in here:
https://www.reddit.com/r/emacs/comments/cdei4p/failed_to_download_gnu_archive_bad_request/

**Comment by freetonik** [comment]
To be honest, I always encounter problems with `undo-tree`, so I ditched it altogether in my personal config. It's still in Castlemacs solely for the purposes of providing a familiar undo experience, not for the tree-based history. I'd love to remove `undo-tree` from Castlemacs.

Can someone suggest a simpler alternative? All I want is undo and redo logic familiar to regular users (rather than Emacs-y undo stack).
